[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.metadata.release]
shared-version = true

[workspace.dependencies]
serde = "1.0.193"
serde_json = "1.0.111"
thiserror = "1.0.51"
anyhow = "1.0.76"
tokio = "1.35.1"
axum = "0.7.4"
