[package]
name = "rust-assistant"
version = "0.1.0"
authors = ["GengTeng <me@gteng.org>"]
edition = "2021"
license = "MIT"
description = "Rust Assistant Service"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
