[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.metadata.release]
shared-version = true

[workspace.dependencies]
serde = "1.0.203"
serde_json = "1.0.117"
anyhow = "1.0.86"
tokio = "1.38.0"
axum = "0.8.1"
axum-extra = "0.10.0"
