[package]
name = "rust-assistant"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
serde = { workspace = true, features = ["derive", "rc"] }
lru = "0.12.1"
reqwest = { version = "0.11.23", features = ["rustls-tls", "json"], default-features = false }

