[package]
name = "rust-assistant-shuttle"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-axum = "0.37.0"
shuttle-runtime = "0.37.0"

rust-assistant = { path = "../rust-assistant", features = ["axum"]}
shuttle-secrets = "0.37.0"
